### ISSUE TITLE
Invoking Judgement: Can only players in a round vote?

### ISSUE THREAD

**Issue by audiodude** [audiodude/tiny-nomic#13]
https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/201_Turn-alternation.md talks about players being *in* a round if their player file exists when the round starts. However, it never stipulates that being in a round is a prerequisite to voting (though I believe this is the intention).

Meanwhile, https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/105_Eligible-voters.md says that every player is an eligible voter and every eligible voter must vote on all rule changes.

By the precedence rules, 105 has a lower number and would mean that everyone in the players directory should be voting on every rule immediately.

I believe that @selfsame is the Judge for this.

@Cardboard @piersb @kgrover @william42 @fonorobert

**Comment by selfsame** [comment]
My judgement of this issue is that:
* per 201 a round must have the vote of every *eligible* player to be resolved
* per 105 players which registered after the round's PR may still cast a vote
