### ISSUE TITLE
Scoring question

### ISSUE THREAD

**Issue by piersb** [audiodude/tiny-nomic#30]
[stands, silhouetted, against the lightning as it strikes a hill behind him]
[a moment]
[thundercrash]

I INVOKE JUDGEMENT!!!!

Per 202, "multiply the result by the fraction of favorable votes it received":

Should that fraction be the fraction of favourable votes out of votes cast, or favourable votes out of current players?

**Comment by piersb** [comment]
@fonorobert, I believe you're the judge on this. @cardboard, if I understand right then your TIMER is currently paused.

**Comment by audiodude** [comment]
It's not clear if the turn timer is paused during judgement. Certainly the rules state that the next player may not begin his or her turn, but they don't say anything about the 48 hours "pausing". So really, if judgement takes too long, it seems logical (but not desirable) that a player could be forced to delay starting his or her turn, and then the 48 hours could expire and they player would be forced to forfeit his or her turn.

**Comment by audiodude** [comment]
Also remember that judges don't have to follow the precedent of past judgements!

**Comment by fonorobert** [comment]
___________
                   \         /
                    )_______(
                    |"""""""|__,.---------.,_.-._
                    |                             '-.
                    |                               ..-'
                    |_______| '-' `'---------'` '-'
                    )"""""""(
                   /_________\
                   `'-------'`
Hear my judgement:

Votes are only the ones that are cast, regardless of who else would have had the right to cast a vote but didn't. Based on this any fraction of the votes is the fraction of the votes cast, not the votes that could have been cast.
For scoring purposes this means the fraction is the total number of "yes" votes divided by the total number of "yes" and "no" votes cast..

**Comment by fonorobert** [comment]
If anyone wishes to invoke judgment on whether the 48 hours are paused or not for the time of judgment, I recommend to open a separate issue for that to keep the two questions separate.
