### ISSUE TITLE
Judgement: Did piersb properly invoke judgement?

### ISSUE THREAD

**Issue by audiodude** [audiodude/tiny-nomic#34]
In the comment: https://github.com/audiodude/tiny-nomic/pull/32#issuecomment-302928498

He clearly wished to invoke judgement, but did not follow the procedure in 214:

> Judgement can be invoked at any time by opening a new issue on the Github repository that hosts the game.

I believe this rule does not suffer from any precedence considerations, since it only further elaborates the process outlined in 212. The way 212 reads, it is not clear how one would actually go about invoking judgement, whereas 214 specifies that precisely.

I believe @kgrover is the judge for the purposes of this judgement, since whether legally or not, @datagrok is taking his turn.

**Comment by piersb** [comment]
I believe my argument at https://github.com/audiodude/tiny-nomic/pull/31#issuecomment-303445274 is relevant to this judgement. Quoting it here for ease-of-access.

212:

_If players disagree about the legality of a move or the interpretation or application of a rule, then the player preceding the one moving is to be the Judge and decide the question. Disagreement for the purposes of this rule may be created by the insistence of any player. This process is called invoking Judgment.

When Judgment has been invoked, the next player may not begin his or her turn without the consent of a majority of the other players._

Per 211 this rule takes precedence over anything 214 may have to say on the matter, so judgement is invoked at the moment that someone insists that it is.

**Comment by audiodude** [comment]
Also there is the implied follow up question which is, if piersb properly invoked judgement, how do we proceed? Don't know if we want to open a separate issue for that when the time comes.

**Comment by datagrok** [comment]
If @kgrover declares that @piersb properly invoked judgment, then the act of taking my turn was illegitimate and it was still @kgrover's turn at the time, meaning @william42, not @kgrover, should have been the judge for this issue. If @william42 were to then disagree with @kgrover's then-illegitimate verdict, my turn would be legitimate, @william42 would not the appropriate judge for this issue, and the resulting paradox would rend a hole in the fabric of time and space.

@bigjust pointed out recently that [rule 107 prevents retroactivity](https://github.com/audiodude/tiny-nomic/pull/31#issuecomment-301958993) but taking a closer look, this only applies to rule changes, not judgments:

> No rule-change may have retroactive application.

The fate of the universe is in your hands

**Comment by william42** [comment]
I'm not sure 212 would allow overturning of a Judgment even by the post-Judgment change of the proper Judge, or even post-Judgment change of heart of the Judge themself. If anyone disagrees, this is a Judgment call, which could be handled either by @kgrover or myself, and I think my own position here is clear.

**Comment by william42** [comment]
Honestly, given the nature of TIMER and FAST, someone not showing up for a judgment seems to be a very real possibility.  There should probably be a way to trigger a (possibly randomized? I could probably set up a randomizer on my linode) reassignment of an absentee Judge

**Comment by audiodude** [comment]
@datagrok I don't find your logic sound.

The rules only talk about what is to happen or what is happening, not what "should have happened". "Should have been the judge for this issue" doesn't make any sense. The judge for the issue is clearly defined, you *were* taking your turn, etc.

Someone ghosting a judgement does seem like a real possibility, and we should have a rule for it, but I don't think it should be random. Just as the judging rules fall back to the previous person in the turn order if the judge is ruled illegitimate, I think that should happen if the judge is a no-show.

**Comment by datagrok** [comment]
> The judge for the issue is clearly defined, you were taking your turn, etc.

If I agree with this, which I think I will for the purposes of the game, it does indeed eliminate the paradoxical situation I was imagining. That's a relief! Thank you 😄 

Though I could imagine someone responding: "I was not 'taking my turn,' rather, I was engaging in illegal turn-like behavior during @kgrover's turn."

> Just as the judging rules fall back to the previous person in the turn order if the judge is ruled illegitimate, I think that should happen if the judge is a no-show.

Agreed. Opened call for voting #36

**Comment by kgrover** [comment]
Sorry, I haven't been able to keep up with the game recently. If I understand this correctly (and I'm not sure I do...), declaring that @piersb did _not_ properly invoke judgement makes the game proceed in a simpler way?

**Comment by audiodude** [comment]
If you decide that @piersb properly invoked judgement, there is a question on how we should proceed, as per the arguments set forward by @datagrok and myself.

If you decide that @piersb did not properly invoke judgement, then it seems that the game moves on to the next turn of @bigjust.

I have my own opinion as to which of these is "simpler", but I feel you should decide that for yourself.

**Comment by datagrok** [comment]
@kgrover: much of the fun in nomic is the inherent rules-lawyering. While I'm eager to progress the game so that all of our players have the creative opportunity to improve and devise new rules, a Judgment that does not make the game proceed in a simpler way also has its own merit, in the challenge we then face to resolve the situation.

That said, in my opinion, a judgment that @piersb did _not_ correctly invoke Judgment will be the simplest way to allow more players to take a turn.

Whether that is the simpler course, and whether the simpler course is most fair, and most fun, is up to you. :smile:

**Comment by kgrover** [comment]
I judge that @piersb did not properly invoke judgement.

**Comment by piersb** [comment]
Drat.

**Comment by datagrok** [comment]
Judgment has been declared so I'm closing this issue. The consequences of this Judgment seem to be that:
- @bigjust is free to begin his turn, and the game will wait for him to do so regardless of the language in FAST, assuming we agree with @audiodude's analysis at https://github.com/audiodude/tiny-nomic/pull/33#issuecomment-304382239. Unless:
- someone declares Judgment before @bigjust begins his turn, or
- @Cardboard votes in the affirmative to overturn this judgment in #36 

We'd better reconcile the language in TIMER/FAST/212-Judging soon, or we might end up again waiting more than 48 hours for a player to begin their turn.

> Drat.

@piersb I don't think there's anything that prevents you from "properly" calling for a judgment about that issue at any time :)
