### ISSUE TITLE
Vote: stop waiting for Judge @kgrover

### ISSUE THREAD

**Issue by datagrok** [audiodude/tiny-nomic#36]
> The Judge's Judgment may be overruled only by a unanimous vote of the other players taken before the next turn is begun. If a Judge's Judgment is overruled, then the player preceding the Judge in the playing order becomes the new Judge for the question, and so on, except that no player is to be Judge during his or her own turn or during the turn of a team-mate.

We are currently unable to begin the next turn because we are waiting for @kgrover to judge #34. For the purpose of moving the game along, I propose that we allow @william42 to decide #34. This is accomplished in this way:

@kgrover is currently the judge for #34. If we achieve a unanimous player vote to overrule their (future) decision (whatever it will be), that will cause judgment to fall to @william42 who (I assume) will perform the judgment quickly.

I expect achieving a unanimous vote will take a while, so in the mean time we can try to get in touch with and summon @kgrover. If they arrive to perform judgment on their issue, the next turn will begin and this vote will be void. (`a unanimous vote of the other players taken before the next turn is begun`) Or to be sure, any players who have not voted on this issue could at that time vote no to reject and close it.

If even one player doesn't like this, they can vote no here to torpedo the motion immediately.

👍

**Comment by william42** [comment]
:+1:

**Comment by audiodude** [comment]
I think this works, because the rule doesn't state that the judgement has to be overruled after it happens.

👍

**Comment by bigjust** [comment]
👍

**Comment by piersb** [comment]
I agree with this interpretation.

👍

**Comment by fonorobert** [comment]
:+1:

**Comment by selfsame** [comment]
:+1:

**Comment by datagrok** [comment]
@kgrover has returned to judge #34! Our only remaining player yet to cast a vote here is @Cardboard. I recommend, @Cardboard, that you leave this un-voted-upon until it is automatically voided by the next player taking their turn after @kgrover's eventual ruling on the issue. But, of course, the game remains interesting if you choose a different course of action.

**Comment by audiodude** [comment]
Actually, @Cardboard could still vote to overturn @kgrover's decision after it is made.

> If they arrive to perform judgment on their issue, the next turn will begin and this vote will be void. (a unanimous vote of the other players taken before the next turn is begun) Or to be sure, any players who have not voted on this issue could at that time vote no to reject and close it.

You left out the third possibility, that at the time that the decision is made, the rest of the players could still vote yes to overturn the judgement.

**Comment by datagrok** [comment]
@audiodude agreed! I should have said, "If they arrive to perform judgment on their issue, the next player is then free to begin their turn, at which time this vote will be void, if we haven't overturned it by then."

**Comment by audiodude** [comment]
The next player has begun (and completed) his turn. There is no way this vote could be valid now. Closing it out.
