### ISSUE TITLE
Whose turn is it?

### ISSUE THREAD

**Issue by audiodude** [audiodude/tiny-nomic#48]
A week has passed since @datagrok commented on the last pull request to be merged:

https://github.com/audiodude/tiny-nomic/pull/42#issuecomment-310569181
> Assuming @selfsame's turn ended at the time the merge was performed, 125.3 hours have elapsed, or 2.6 48-hour periods, meaning FAST has forfeited @fonorobert and @piersb's turns and now @Cardboard has 18.7 hours remaining to submit a rule before their turn is also forfeit and @william42's turn will begin.

Since then, it appears that several turns have been forfeited in succession, since no one has brought a new rule proposal.

This post is an attempt to enumerate who has forfeited their turn and whose turn it is right now.

The merge was performed on June 17 at 4:09 PM PDT
It is now June 29 at 3:50 PM PDT

287.68 hours have elapsed
287.68 / 48 = 5.993, or 5.9, 48 hour periods

This means 5 user's turns have been forfeited: @fonorobert @piersb @Cardboard @william42 @kgrover 

@datagrok has less than 20 minutes to submit a rule proposal. If not, the turn will be forfeit and it will become @bigjust's turn.

So all users see this: @audiodude @sashahart @selfsame

**Comment by datagrok** [comment]
Arrgh! Can't believe I missed me own turn.

**Comment by william42** [comment]
In my defense, I'm getting married on the 8th and preparation for that kinda takes precedence.

**Comment by datagrok** [comment]
I was just a few hours too late to propose me new rule establishing that this nomic game is to take precedence over all sporting events, nuptials, and national holidaise (congratulations @william42!)

**Comment by audiodude** [comment]
@william42 is in violation of VOWEL, minus 2 points!

**Comment by audiodude** [comment]
According to datagrok's script:

@bigjust forfeited their turn at  Jul 01, 04:09PM.

And

@sashahart must begin their turn by Jul 03, 04:09PM.

**Comment by audiodude** [comment]
Minus two points for me!

**Comment by datagrok** [comment]
I'm curious: are we all just occupied elsewhere, or failing to get adequate reminders that our turn is approaching, or do we just have no ideas for new rules?

Because I'm sitting on like seven different rules changes I want to propose! 😄

**Comment by audiodude** [comment]
I feel like it's a combination of the first two, and not so much the latter.

Which reminds me, @sashahart has forfeited their turn and it is now my turn!

**Comment by piersb** [comment]
Lack of reminders for me.

**Comment by audiodude** [comment]
Or maybe VOWEL has just had a chilling effect.

Minus two more points for me.
